/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smpaint2d;

import SM.PPN.graficos.ShapePPN;
import java.awt.Point;

/**
 * Clase para asignar una nueva posición a la figura
 * @author Pedro Parrilla
 */
public class TPanelPPN extends javax.swing.JDialog {

    /**
     * Creates new form TPanelPPN
     * @param parent
     * @param modal
     * @param shape
     */
    public TPanelPPN(java.awt.Frame parent, boolean modal, ShapePPN shape) {
        super(parent, modal);
        initComponents();
        jSpinner1.setValue((int) shape.getLocation().x);
        jSpinner2.setValue((int) shape.getLocation().y);
        jPanel1.setSize(150, 150);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel2 = new javax.swing.JPanel();
        jBSelect = new javax.swing.JButton();
        jBCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Pos X");
        jPanel1.add(jLabel1);
        jPanel1.add(jSpinner1);

        jLabel2.setText("Pos Y");
        jPanel1.add(jLabel2);
        jPanel1.add(jSpinner2);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jBSelect.setText("Seleccionar");
        jBSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSelectActionPerformed(evt);
            }
        });
        jPanel2.add(jBSelect);

        jBCancel.setText("Cancelar");
        jBCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelActionPerformed(evt);
            }
        });
        jPanel2.add(jBCancel);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSelectActionPerformed
        x = (int) jSpinner1.getValue();
        y = (int) jSpinner2.getValue();
        this.dispose();
    }//GEN-LAST:event_jBSelectActionPerformed

    private void jBCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBCancelActionPerformed

    /**
     *Devolución del valor x seleccionado
     * @return 
     */
    
    public int getPX(){
        return x;
    }
    
    public int getPY(){
        return y;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancel;
    private javax.swing.JButton jBSelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    // End of variables declaration//GEN-END:variables
    int x, y;
}
