/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package smpaint2d;
import SM.PPN.iu.LienzoImagenPPN;

/**
 *
 * @author Pedro Parrilla
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creacion del objeto VentanaInterna
     * @param vp
     */
    public VentanaInterna( VentanaPrincipal vp ) {
        initComponents();
        //setSize(300, 300);
        parent = vp;
    }
    
    public VentanaInterna( VentanaPrincipal vp, int w, int h ){
        this(vp);
        lienzo2D1.setAreaClip(w, h);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2D1 = new SM.PPN.iu.LienzoImagenPPN();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(300, 300));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jScrollPane1.setPreferredSize(new java.awt.Dimension(300, 300));

        lienzo2D1.setPreferredSize(new java.awt.Dimension(200, 200));
        lienzo2D1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lienzo2D1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout lienzo2D1Layout = new javax.swing.GroupLayout(lienzo2D1);
        lienzo2D1.setLayout(lienzo2D1Layout);
        lienzo2D1Layout.setHorizontalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        lienzo2D1Layout.setVerticalGroup(
            lienzo2D1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2D1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        parent.setEnableButtoms(lienzo2D1.getDrawtype(), 
                lienzo2D1.getIsRelleno(), lienzo2D1.getIsRender(), 
                lienzo2D1.getIsTransparent(), lienzo2D1.getgTrazo(), 
                lienzo2D1.getDirDegradado(), lienzo2D1.gettTrazo());
        parent.addToComboBoxItem(lienzo2D1.getvShape());
    }//GEN-LAST:event_formInternalFrameActivated

    private void lienzo2D1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2D1MouseReleased
        parent.addToComboBoxItem(lienzo2D1.getvShape());
    }//GEN-LAST:event_lienzo2D1MouseReleased

    public LienzoImagenPPN getLienzo(){
        return lienzo2D1;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private SM.PPN.iu.LienzoImagenPPN lienzo2D1;
    // End of variables declaration//GEN-END:variables
    private VentanaPrincipal parent = null;
}
